export const ADMIN_ROUTE ='/admin'
export const LOGIN_ROUTE ='/login'
export const REGISTRATION_ROUTE ='/registration'
export const MAIN_ROUTE ='/main'
export const FLATS_ROUTE ='/flats'
export const FLATPAGE_ROUTE ='/flatpage'
export const FEEDBACK_ROUTE='/feedback'
export const NEWS_ROUTE='news'
